version: '3.9'

services:
  react-app-dev:
    container_name: my-awesome-app-dev-jlm
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '/app/node_modules'
      - './:/app'
    ports:
      - "3002:8080"
  
  react-app-test:
    container_name: my-awesome-app-test-jlm
    image: my-awesome-app-jlm_react-app-dev
    depends_on:
      - react-app-dev
    volumes:
      - '/app/node_modules'
      - './:/app'
    command: [ "npm", "test"]

