version: '3.9'



services:
  web:
    container_name: my-awesome-app-dev-jlm

    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '3001:3000'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

  test:
    container_name: my-awesome-app-dev-jlm
    depends_on:
      - "web"
    image: my-awesome-app-jlm_web
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: ["npm", "test"]