version: '3.9'



services:
  dev:
    container_name: my-awesome-app-jlm-dev

    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - '80:8080'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

  test:
    container_name: my-awesome-app-jlm-dev
    depends_on:
      - "dev"
    image: my-awesome-app-jlm-dev_dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: ["npm", "test"]