
env:
  APP_NAME: my-awesome-app
  AWS_REGION: us-east-2
  AWS_PLATFORM: Docker
  PIPELINE_ID: $GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
  DATE_STAMP: $(date +%s)

on:
  workflow_dispatch:

jobs:
  deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Configure AWS credentials and version label
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secrets-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - run: /
          echo "aws_version_label=${{env.APP_NAME}}-${{env.PIPELINE_ID}}" >> $GITHUB_ENV
          echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV

      - name: Login to Docker
      - run: zip -r ${{env.APP_NAME}}.zip  app.js Dockerfile .dockerignore package.json

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with: 
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.APP_NAME }}
          environment_name: my-awesome-app
          version_label: ${{ env.aws_version_label }}
          region: ${{ env.AWS_REGION }}
          deployment_package: ${{ DOCKER_COMPOSE_FILE }}