


name: Docker Dev Image CI

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

  workflow_dispatch:

env:
  DATE_STAMP: $(date +%s)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          - name: Env variables
            run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV
          - name: Build the Docker image
            run: docker build -f Dockerfile-dev -t jaredmartin/my-awesome-app-jlm:latest .
          - name: Add "date-stamp" tag to the image.
            run: docker image tag jaredmartin/my-awesome-app-jlm:latest jaredmartin/my-awesome-app-jlm:${{ env.date-stamp }}
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_TOKEN }}
          - name: Push the Docker image to Docker Hub
            run: docker push --all-tags jaredmartin/my-awesome-app-jlm