# This is a basic workflow to help you get started with Actions

name: Build Prod Image & Deploy to Docker Hub
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Env variables
      run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jaredmartin/my-awesome-app-jlm:latest 
    - name: Add "date-stamp" tag to the image
      run: docker image tag jaredmartin/my-awesome-app-jlm:latest jaredmartin/my-awesome-app-jlm:${{ env.date-stamp }}
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Push the Docker image to Docker Hub
      run: docker push --all-tags jaredmartin/my-awesome-app-jlm
